"""Report email delivery: SMTP with the PDF attached, or an ``.eml`` file when SMTP is absent.

:func:`send_report_email` never raises; it returns a :class:`MailResult` whose ``status`` is
``SENT`` (the SMTP server accepted the message), ``SAVED`` (``settings.smtp_configured`` is
False: the complete message was written to ``settings.outbox_dir`` as
``report-<id>-<UTC timestamp>.eml``, marked ``X-Unsent: 1`` so mail clients open it as a draft)
or ``FAILED`` (with a short ``error``; the SMTP password is never included).
:func:`send_test_email` sends (or saves, as ``test-<timestamp>.eml``) a short message without
attachment to check the set-up (CLI ``send-test-email``).

SMTP: implicit TLS (``smtplib.SMTP_SSL``) when ``settings.smtp_ssl``; otherwise ``smtplib.SMTP``
on ``smtp_port`` upgraded with STARTTLS when ``smtp_starttls`` (default; a server without
STARTTLS fails rather than falling back to plain text). ``login`` only when ``smtp_user`` is set.
Every network operation uses ``smtp_timeout_s``. Certificates are verified
(``ssl.create_default_context``).
"""

from __future__ import annotations

import logging
import re
import smtplib
import ssl
from dataclasses import dataclass
from datetime import datetime, timezone
from email.message import EmailMessage
from email.utils import format_datetime, make_msgid, parseaddr

from tactidose.config import Settings

log = logging.getLogger(__name__)

__all__ = [
    "STATUS_FAILED",
    "STATUS_SAVED",
    "STATUS_SENT",
    "MailResult",
    "build_message",
    "normalize_email",
    "send_report_email",
    "send_test_email",
]

STATUS_SENT = "SENT"
STATUS_SAVED = "SAVED"
STATUS_FAILED = "FAILED"
DEFAULT_FROM = "TactiDose <no-reply@tactidose.local>"
TEST_SUBJECT = "TactiDose test email"
TEST_BODY = (
    "This is a test message from TactiDose.\n"
    "If you can read it, report emails can be delivered to this address.\n"
    "\n"
    "Prototype — not a medical device. Generated by TactiDose.\n"
)

_EMAIL_RE = re.compile(
    r"^[A-Za-z0-9.!#$%&'*+/=?^_`{|}~-]+@"
    r"[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$"
)
_MAX_ERROR = 300


@dataclass(frozen=True)
class MailResult:
    status: str                       # SENT | SAVED | FAILED
    error: str | None = None
    path: str | None = None           # the .eml file when SAVED
    message_id: str | None = None

    @property
    def ok(self) -> bool:
        return self.status in (STATUS_SENT, STATUS_SAVED)


def normalize_email(value: object) -> str | None:
    """Lower-cased address if ``value`` is exactly one plain email address, else ``None``.

    Rejects display names, lists, whitespace and CR/LF (header injection)."""
    if not isinstance(value, str):
        return None
    v = value.strip()
    if not v or len(v) > 254 or any(c in v for c in " \t\r\n<>,;\"()[]\\:"):
        return None
    if v.count("@") != 1 or not _EMAIL_RE.match(v):
        return None
    local, _, domain = v.partition("@")
    if len(local) > 64 or local.startswith(".") or local.endswith(".") or ".." in local:
        return None
    return f"{local}@{domain}".lower()


def build_message(
    settings: Settings,
    *,
    to: str,
    subject: str,
    body: str,
    pdf_bytes: bytes | None = None,
    filename: str = "tactidose-report.pdf",
    now: datetime | None = None,
) -> EmailMessage:
    """The message to send; the PDF is attached when ``pdf_bytes`` is given."""
    sender = _from_address(settings)
    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = to
    msg["Subject"] = _header_text(subject) or "TactiDose report"
    msg["Date"] = format_datetime((now or datetime.now(timezone.utc)).astimezone(timezone.utc))
    msg["Message-ID"] = make_msgid(domain=_domain_of(sender))   # explicit domain: no slow getfqdn()
    msg["X-Mailer"] = "TactiDose"
    msg.set_content(body or "")
    if pdf_bytes is not None:
        msg.add_attachment(bytes(pdf_bytes), maintype="application", subtype="pdf",
                           filename=_safe_filename(filename))
    return msg


def send_report_email(
    settings: Settings,
    *,
    to: str,
    subject: str,
    body: str,
    pdf_bytes: bytes,
    filename: str,
    now: datetime | None = None,
    report_id: int | None = None,
) -> MailResult:
    """Send (or save) one report email to one recipient. Never raises."""
    stem = f"report-{int(report_id)}" if report_id is not None else "report"
    return _deliver(settings, to=to, subject=subject, body=body, pdf_bytes=bytes(pdf_bytes), filename=filename,
                    now=now, stem=stem)


def send_test_email(settings: Settings, to_email: str, *, now: datetime | None = None) -> MailResult:
    """Check the email set-up with one short message (no attachment). Never raises."""
    return _deliver(settings, to=to_email, subject=TEST_SUBJECT, body=TEST_BODY, pdf_bytes=None,
                    filename="", now=now, stem="test")


def _deliver(settings: Settings, *, to: str, subject: str, body: str, pdf_bytes: bytes | None, filename: str,
             now: datetime | None, stem: str) -> MailResult:
    address = normalize_email(to)
    if address is None:
        return MailResult(STATUS_FAILED, error="invalid recipient address")
    try:
        msg = build_message(settings, to=address, subject=subject, body=body, pdf_bytes=pdf_bytes,
                            filename=filename, now=now)
    except Exception as exc:  # noqa: BLE001 - contract: never raises
        log.warning("report email could not be built: %s", type(exc).__name__)
        return MailResult(STATUS_FAILED, error=f"could not build the email ({type(exc).__name__})")
    if not settings.smtp_configured:
        return _save_eml(settings, msg, now=now, stem=stem)
    return _send_smtp(settings, msg)


# --------------------------------------------------------------------------- internals


def _send_smtp(settings: Settings, msg: EmailMessage) -> MailResult:
    host = str(settings.smtp_host)
    port = int(settings.smtp_port)
    timeout = float(settings.smtp_timeout_s)
    password = settings.smtp_password.get_secret_value() if settings.smtp_password else ""
    smtp: smtplib.SMTP | None = None
    try:
        if settings.smtp_ssl:
            smtp = smtplib.SMTP_SSL(host, port, timeout=timeout, context=ssl.create_default_context())
            smtp.ehlo()
        else:
            smtp = smtplib.SMTP(host, port, timeout=timeout)
            smtp.ehlo()
            if settings.smtp_starttls:
                smtp.starttls(context=ssl.create_default_context())
                smtp.ehlo()
            elif settings.smtp_user:
                log.warning("SMTP login to %s:%s without TLS (SMTP_STARTTLS and SMTP_SSL are off)", host, port)
        if settings.smtp_user:
            smtp.login(settings.smtp_user, password)
        refused = smtp.send_message(msg)
    except Exception as exc:  # noqa: BLE001 - contract: SMTP problems become FAILED
        error = _redact(f"{type(exc).__name__}: {exc}", password)[:_MAX_ERROR]
        log.warning("report email to %s via %s:%s failed: %s", msg["To"], host, port, error)
        return MailResult(STATUS_FAILED, error=error, message_id=msg["Message-ID"])
    finally:
        if smtp is not None:
            _quit(smtp)
    if refused:
        error = _redact(f"recipient refused: {refused}", password)[:_MAX_ERROR]
        log.warning("report email: %s", error)
        return MailResult(STATUS_FAILED, error=error, message_id=msg["Message-ID"])
    log.info("report email sent to %s via %s:%s", msg["To"], host, port)
    return MailResult(STATUS_SENT, message_id=msg["Message-ID"])


def _quit(smtp: smtplib.SMTP) -> None:
    try:
        smtp.quit()
    except Exception:  # noqa: BLE001 - the message outcome is already decided
        try:
            smtp.close()
        except Exception as exc:  # noqa: BLE001
            log.debug("SMTP close failed: %s", type(exc).__name__)


def _save_eml(settings: Settings, msg: EmailMessage, *, now: datetime | None, stem: str) -> MailResult:
    try:
        outbox = settings.outbox_dir
        outbox.mkdir(parents=True, exist_ok=True)
        msg["X-Unsent"] = "1"
        msg["X-TactiDose-Delivery"] = "saved: SMTP is not configured"
        data = msg.as_bytes(policy=msg.policy.clone(linesep="\r\n"))
        stamp = (now or datetime.now(timezone.utc)).astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        base = f"{stem}-{stamp}"
        for n in range(1, 1000):
            path = outbox / (f"{base}.eml" if n == 1 else f"{base}-{n}.eml")
            try:
                with open(path, "xb") as fh:
                    fh.write(data)
            except FileExistsError:
                continue
            log.info("SMTP not configured: report email for %s saved to %s", msg["To"], path)
            return MailResult(STATUS_SAVED, path=str(path), message_id=msg["Message-ID"])
        return MailResult(STATUS_FAILED, error="could not choose a unique .eml file name")
    except Exception as exc:  # noqa: BLE001 - contract: never raises
        log.warning("report email could not be saved to %s: %s", settings.outbox_dir, exc)
        return MailResult(STATUS_FAILED, error=f"could not save the email: {type(exc).__name__}: {exc}"[:_MAX_ERROR])


def _from_address(settings: Settings) -> str:
    for candidate in (settings.smtp_from, settings.smtp_user):
        text = _header_text(candidate or "")
        if text and "@" in parseaddr(text)[1]:
            return text
    return DEFAULT_FROM


def _domain_of(address: str) -> str:
    domain = parseaddr(address)[1].rpartition("@")[2].strip().lower()
    return domain if re.fullmatch(r"[a-z0-9.-]{1,253}", domain or "") else "tactidose.local"


def _header_text(value: str) -> str:
    return re.sub(r"\s+", " ", str(value or "")).strip()[:250]


def _safe_filename(name: str) -> str:
    stem = re.sub(r"[^A-Za-z0-9._-]+", "-", str(name or "")).strip(".-")[:100]
    if not stem:
        stem = "tactidose-report.pdf"
    return stem if stem.lower().endswith(".pdf") else f"{stem}.pdf"


def _redact(text: str, *secrets: str) -> str:
    for secret in secrets:
        if secret:
            text = text.replace(secret, "***")
    return text
