"""PDF rendering of a report with fpdf2 (offline, Windows / macOS / Linux).

Layout (US Letter, portrait): title block (patient, period, generated at/by, device), summary
tiles, adherence-by-day bar chart drawn with fpdf2 primitives + the same numbers as a table,
per-medication table, missed / failed / uncertain list, refused requests, inventory, the
narrative, timestamped conversation excerpts (patient vs assistant), an "About this report"
section with definitions, and on every page the footer disclaimer
``Prototype — not a medical device. Generated by TactiDose.`` plus "Page X of Y".

Readability: 11 pt body text (9–10 pt in tables), black-on-white, state is always written as
words (never colour alone), the chart has direct labels for the days that matter and a table
twin, and the PDF has a title, language and an outline (bookmarks per section).

Unicode: a TrueType font from the OS is embedded when one is found (Arial / Segoe UI /
Calibri on Windows, DejaVu / Liberation / Noto on Linux, Arial / Arial Unicode / Helvetica on
macOS). Characters it lacks are drawn from OS fallback fonts registered on demand (symbols and
emoji outlines, CJK, Korean, Indic...), otherwise replaced: symbols by their Unicode name
("[nauseated face]"), anything else by "?". Variation selectors, joiners and skin-tone
modifiers are dropped. Without any TTF font (or if rendering with it fails) the built-in
Helvetica is used and text is sanitised to its Windows-1252 (latin-1 superset) encoding.
"""

from __future__ import annotations

import logging
import math
import os
import sys
import unicodedata
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import datetime
from functools import lru_cache
from pathlib import Path
from typing import Any

from fpdf import FPDF, FontFace
from fpdf.enums import XPos, YPos

from tactidose.reports.data import (
    ReportData,
    fmt_date,
    fmt_datetime,
    fmt_day,
    fmt_pct,
    fmt_time,
)
from tactidose.reports.narrative import Excerpt, Narrative, reason_label, source_label

log = logging.getLogger(__name__)

__all__ = [
    "DISCLAIMER",
    "FontFile",
    "FontPaths",
    "find_system_fonts",
    "render_report_pdf",
]

DISCLAIMER = "Prototype — not a medical device. Generated by TactiDose."

# Colours (validated for contrast on white: bar 4.4:1, secondary ink 7.9:1).
INK = (11, 11, 11)
INK2 = (82, 81, 78)
MUTED = (137, 135, 129)
GRID = (225, 224, 217)
AXIS = (195, 194, 183)
TILE = (240, 239, 236)
BAR = (42, 120, 214)

_FAMILY = "tdsans"
_CORE_FAMILY = "helvetica"
_BOTTOM_MARGIN = 20.0
_MAX_TABLE_ROWS = 120
_CELL_PAD = 1.2
#: Longest word used for column sizing; longer words wrap inside the cell.
_MAX_WORD_MM = 34.0


# --------------------------------------------------------------------------- fonts


@dataclass(frozen=True)
class FontFile:
    path: Path
    index: int = 0          # face number inside a .ttc collection


@dataclass(frozen=True)
class FontPaths:
    """Fonts to embed. ``regular=None`` means the built-in Helvetica (cp1252 text only)."""

    regular: FontFile | None = None
    bold: FontFile | None = None
    fallbacks: tuple[FontFile, ...] = ()


def _win_dirs() -> list[Path]:
    root = os.environ.get("WINDIR") or os.environ.get("SystemRoot") or r"C:\Windows"
    dirs = [Path(root) / "Fonts"]
    local = os.environ.get("LOCALAPPDATA")
    if local:
        dirs.append(Path(local) / "Microsoft" / "Windows" / "Fonts")
    return dirs


def _home() -> Path | None:
    try:
        return Path.home()
    except (RuntimeError, KeyError, OSError):   # no resolvable home directory (service accounts)
        return None


def _linux_dirs() -> list[Path]:
    home = _home()
    user = [home / ".local" / "share" / "fonts", home / ".fonts"] if home else []
    return [Path("/usr/share/fonts"), Path("/usr/local/share/fonts"), *user]


def _mac_dirs() -> list[Path]:
    home = _home()
    user = [home / "Library" / "Fonts"] if home else []
    return [Path("/System/Library/Fonts/Supplemental"), Path("/Library/Fonts"), Path("/System/Library/Fonts"), *user]


_WIN_PRIMARY = (("arial.ttf", "arialbd.ttf"), ("segoeui.ttf", "segoeuib.ttf"), ("calibri.ttf", "calibrib.ttf"),
                ("verdana.ttf", "verdanab.ttf"), ("tahoma.ttf", "tahomabd.ttf"),
                ("DejaVuSans.ttf", "DejaVuSans-Bold.ttf"))
_WIN_FALLBACK = ("seguisym.ttf", "segoeui.ttf", "msyh.ttc", "malgun.ttf", "Nirmala.ttc", "ebrima.ttf",
                 "seguihis.ttf")
_LINUX_PRIMARY = (
    ("truetype/dejavu/DejaVuSans.ttf", "truetype/dejavu/DejaVuSans-Bold.ttf"),
    ("TTF/DejaVuSans.ttf", "TTF/DejaVuSans-Bold.ttf"),
    ("dejavu/DejaVuSans.ttf", "dejavu/DejaVuSans-Bold.ttf"),
    ("dejavu-sans-fonts/DejaVuSans.ttf", "dejavu-sans-fonts/DejaVuSans-Bold.ttf"),
    ("truetype/liberation/LiberationSans-Regular.ttf", "truetype/liberation/LiberationSans-Bold.ttf"),
    ("truetype/liberation2/LiberationSans-Regular.ttf", "truetype/liberation2/LiberationSans-Bold.ttf"),
    ("liberation-sans/LiberationSans-Regular.ttf", "liberation-sans/LiberationSans-Bold.ttf"),
    ("truetype/noto/NotoSans-Regular.ttf", "truetype/noto/NotoSans-Bold.ttf"),
    ("noto/NotoSans-Regular.ttf", "noto/NotoSans-Bold.ttf"),
    ("truetype/freefont/FreeSans.ttf", "truetype/freefont/FreeSansBold.ttf"),
)
_LINUX_FALLBACK = (
    "truetype/dejavu/DejaVuSans.ttf", "TTF/DejaVuSans.ttf", "dejavu/DejaVuSans.ttf",
    "truetype/noto/NotoSansSymbols2-Regular.ttf", "truetype/noto/NotoSansSymbols-Regular.ttf",
    "opentype/noto/NotoSansCJK-Regular.ttc", "noto-cjk/NotoSansCJK-Regular.ttc",
    "truetype/ancient-scripts/Symbola_hint.ttf", "truetype/freefont/FreeSerif.ttf",
)
_MAC_PRIMARY = (("Arial.ttf", "Arial Bold.ttf"), ("Arial Unicode.ttf", None), ("Verdana.ttf", "Verdana Bold.ttf"),
                ("Helvetica.ttc", "Helvetica.ttc"))
_MAC_FALLBACK = ("Arial Unicode.ttf", "Apple Symbols.ttf")


def _first(dirs: Sequence[Path], name: str) -> Path | None:
    for d in dirs:
        p = d / name
        try:
            if p.is_file():
                return p
        except OSError:
            continue
    return None


def _ttc_face(path: Path, want_bold: bool) -> int:
    """Face index of the (non-italic) regular or bold member of a .ttc collection (0 if unknown)."""
    if path.suffix.lower() != ".ttc":
        return 0
    try:
        from fontTools.ttLib import TTCollection

        coll = TTCollection(str(path), lazy=True)
        for i, font in enumerate(coll.fonts):
            sub = (font["name"].getDebugName(2) or "").strip().lower()
            if sub == ("bold" if want_bold else "regular"):
                return i
    except Exception:  # noqa: BLE001 - unreadable collection: use the first face
        return 0
    return 0


@lru_cache(maxsize=1)
def find_system_fonts() -> FontPaths:
    """Best available OS fonts (cached; cheap filesystem checks only)."""
    if sys.platform.startswith("win"):
        dirs, primary, fallback = _win_dirs(), _WIN_PRIMARY, _WIN_FALLBACK
    elif sys.platform == "darwin":
        dirs, primary, fallback = _mac_dirs(), _MAC_PRIMARY, _MAC_FALLBACK
    else:
        dirs, primary, fallback = _linux_dirs(), _LINUX_PRIMARY, _LINUX_FALLBACK
    regular = bold = None
    for reg_name, bold_name in primary:
        reg = _first(dirs, reg_name)
        if reg is None:
            continue
        regular = FontFile(reg, _ttc_face(reg, False))
        b = _first(dirs, bold_name) if bold_name else None
        bold = FontFile(b, _ttc_face(b, True)) if b is not None else None
        break
    if regular is None and not sys.platform.startswith("win") and sys.platform != "darwin":
        regular = _search_linux_dejavu(dirs)
    fallbacks: list[FontFile] = []
    for name in fallback:
        p = _first(dirs, name)
        if p is not None and (regular is None or p != regular.path) and all(f.path != p for f in fallbacks):
            fallbacks.append(FontFile(p, 0))
    found = FontPaths(regular, bold, tuple(fallbacks))
    log.info("report PDF fonts: %s (bold %s), %d fallback font(s)",
             regular.path if regular else "built-in Helvetica", bold.path if bold else "-", len(fallbacks))
    return found


def _search_linux_dejavu(dirs: Sequence[Path]) -> FontFile | None:
    for d in dirs:
        try:
            for p in d.rglob("DejaVuSans.ttf"):
                return FontFile(p, 0)
        except OSError:
            continue
    return None


@lru_cache(maxsize=32)
def _cmap(path: Path, index: int) -> frozenset[int]:
    try:
        from fontTools.ttLib import TTFont

        font = TTFont(str(path), fontNumber=index, lazy=True)
        try:
            return frozenset((font.getBestCmap() or {}).keys())
        finally:
            font.close()
    except Exception as exc:  # noqa: BLE001 - an unreadable fallback font just covers nothing
        log.debug("cannot read cmap of %s: %s", path, exc)
        return frozenset()


_ASCII = {
    "\u2264": "<=", "\u2265": ">=", "\u2192": "->", "\u2190": "<-", "\u2194": "<->", "\u21d2": "=>",
    "\u2212": "-", "\u2010": "-", "\u2011": "-", "\u2012": "-", "\u2015": "-", "\u2043": "-",
    "\u2032": "'", "\u2033": '"', "\u2044": "/", "\u2248": "~", "\u2260": "!=", "\u00a0": " ",
    "\u2002": " ", "\u2003": " ", "\u2009": " ", "\u202f": " ", "\u25cf": "*", "\u25cb": "o",
    "\u2219": "*",
}


class _FontKit:
    """Registers the fonts on one FPDF document and makes any text safe to draw with them."""

    def __init__(self, pdf: FPDF, paths: FontPaths) -> None:
        self.pdf = pdf
        self.unicode = paths.regular is not None
        self._pending = list(paths.fallbacks)
        self._registered: list[tuple[str, frozenset[int]]] = []
        self._chars: dict[str, str] = {}
        if paths.regular is not None:
            bold = paths.bold or paths.regular
            pdf.add_font(_FAMILY, "", str(paths.regular.path), collection_font_number=paths.regular.index)
            pdf.add_font(_FAMILY, "B", str(bold.path), collection_font_number=bold.index)
            self.family = _FAMILY
            self._covered = frozenset(pdf.fonts[_FAMILY].cmap) & frozenset(pdf.fonts[_FAMILY + "B"].cmap)
        else:
            self.family = _CORE_FAMILY
            self._covered = frozenset()
            pdf.core_fonts_encoding = "windows-1252"

    def clean(self, text: Any) -> str:
        if text is None:
            return ""
        s = unicodedata.normalize("NFC", str(text))
        out = []
        for ch in s:
            r = self._chars.get(ch)
            if r is None:
                r = self._resolve(ch)
                self._chars[ch] = r
            out.append(r)
        return "".join(out)

    def _resolve(self, ch: str) -> str:
        if ch == "\n":
            return "\n"
        if ch in "\t\x0b\x0c":
            return " "
        cp = ord(ch)
        cat = unicodedata.category(ch)
        if cat in ("Zl", "Zp"):
            return "\n"
        if cat in ("Cc", "Cf", "Cs", "Co", "Cn") or 0xFE00 <= cp <= 0xFE0F or 0xE0100 <= cp <= 0xE01EF \
                or 0x1F3FB <= cp <= 0x1F3FF:
            return ""
        if self.unicode:
            if cp in self._covered or self._fallback_covers(cp):
                return ch
            if cat in ("Mn", "Me", "Mc"):
                return ""
            if cat == "Zs":
                return " "
            return self._replacement(ch)
        if _cp1252(ch):
            return ch
        if ch in _ASCII:
            return _ASCII[ch]
        if cat in ("Mn", "Me", "Mc"):
            return ""
        if cat == "Zs":
            return " "
        base = "".join(c for c in unicodedata.normalize("NFKD", ch) if not unicodedata.combining(c))
        if base and all(_cp1252(c) for c in base):
            return base
        return self._replacement(ch)

    def _replacement(self, ch: str) -> str:
        if unicodedata.category(ch).startswith("S"):
            name = unicodedata.name(ch, "")
            if name:
                return f"[{name.lower()}]"
        return "?"

    def _fallback_covers(self, cp: int) -> bool:
        for _, cmap in self._registered:
            if cp in cmap:
                return True
        for i, ff in enumerate(self._pending):
            if cp in _cmap(ff.path, ff.index):
                del self._pending[i]
                name = f"tdfb{len(self._registered)}"
                try:
                    self.pdf.add_font(name, "", str(ff.path), collection_font_number=ff.index)
                except Exception as exc:  # noqa: BLE001 - skip a fallback font fpdf2 cannot use
                    log.warning("fallback font %s unusable: %s", ff.path, exc)
                    return False
                cmap = frozenset(self.pdf.fonts[name].cmap)
                self._registered.append((name, cmap))
                self.pdf.set_fallback_fonts([n for n, _ in self._registered], exact_match=False)
                return cp in cmap
        return False


def _cp1252(ch: str) -> bool:
    try:
        ch.encode("cp1252")
    except UnicodeEncodeError:
        return False
    return True


# --------------------------------------------------------------------------- document


class _ReportPDF(FPDF):
    def __init__(self) -> None:
        super().__init__(orientation="P", unit="mm", format="Letter")
        self.kit: _FontKit | None = None
        self.running_header = ""
        self._fitted_header: str | None = None
        self.footer_text = ""

    def header(self) -> None:
        if self.page_no() == 1 or self.kit is None:
            return
        self.set_y(8)
        self.set_font(self.kit.family, "", 9)
        self.set_text_color(*INK2)
        if self._fitted_header is None:
            self._fitted_header = _fit_text(self, self.running_header, self.epw)
        self.cell(0, 5, self._fitted_header, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*GRID)
        self.set_line_width(0.2)
        self.line(self.l_margin, 14, self.w - self.r_margin, 14)
        self.set_y(self.t_margin)
        self.set_text_color(*INK)

    def footer(self) -> None:
        if self.kit is None:
            return
        self.set_y(-14)
        self.set_draw_color(*GRID)
        self.set_line_width(0.2)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.set_y(-12.5)
        self.set_font(self.kit.family, "", 9)
        self.set_text_color(*INK2)
        page = f"Page {self.page_no()} of {{nb}}"
        width = self.epw - 30
        self.cell(width, 5, self.footer_text, align="L")
        self.cell(30, 5, page, align="R")
        self.set_text_color(*INK)


def render_report_pdf(
    data: ReportData,
    stats: dict[str, Any],
    narrative: Narrative,
    excerpts: Sequence[Excerpt] = (),
    *,
    fonts: FontPaths | None = None,
) -> bytes:
    """Render the report; returns the PDF bytes. Retries with the built-in font if the TTF path fails."""
    paths = fonts if fonts is not None else find_system_fonts()
    if paths.regular is not None:
        try:
            return _Renderer(data, stats, narrative, excerpts, paths).render()
        except Exception as exc:  # noqa: BLE001 - font trouble must not cost the report
            log.warning("PDF rendering with %s failed (%s: %s); retrying with the built-in font",
                        paths.regular.path, type(exc).__name__, exc)
    return _Renderer(data, stats, narrative, excerpts, FontPaths()).render()


class _Renderer:
    def __init__(self, data: ReportData, stats: dict[str, Any], narrative: Narrative,
                 excerpts: Sequence[Excerpt], paths: FontPaths) -> None:
        self.data = data
        self.stats = stats
        self.narrative = narrative
        self.excerpts = list(excerpts)
        self.pdf = _ReportPDF()
        self.kit = _FontKit(self.pdf, paths)
        self.t: Callable[[Any], str] = self.kit.clean
        self.pdf.kit = self.kit

    # ------------------------------------------------------------------ top level
    def render(self) -> bytes:
        pdf, d = self.pdf, self.data
        start, end = d.local(d.period_start), d.local(d.period_end)
        period_short = f"{fmt_date(start)} – {fmt_date(end)}"
        pdf.running_header = self.t(f"TactiDose report — {d.patient.display_name} — {period_short}")
        pdf.footer_text = self.t(DISCLAIMER)
        pdf.set_margins(16, 16, 16)
        pdf.set_auto_page_break(True, margin=_BOTTOM_MARGIN)
        pdf.set_title(f"TactiDose report — {d.patient.display_name} — last {_days(d.days)}")
        pdf.set_author("TactiDose")
        pdf.set_creator("TactiDose")
        pdf.set_subject("Pill drop and adherence report (prototype, not a medical device)")
        pdf.set_keywords("TactiDose, report, adherence, pill drops")
        pdf.set_lang("en")
        try:
            pdf.set_creation_date(d.generated_at)
        except Exception as exc:  # noqa: BLE001 - metadata only
            log.debug("PDF creation date not set: %s", exc)
        pdf.add_page()
        self._title_block()
        self._summary()
        self._adherence()
        self._medications()
        self._issues()
        self._refused()
        self._inventory()
        self._narrative()
        self._excerpts()
        self._about()
        return bytes(pdf.output())

    # ------------------------------------------------------------------ primitives
    def _font(self, size: float, bold: bool = False, color: tuple[int, int, int] = INK) -> None:
        self.pdf.set_font(self.kit.family, "B" if bold else "", size)
        self.pdf.set_text_color(*color)

    def _para(self, text: str, *, size: float = 11, bold: bool = False, color: tuple[int, int, int] = INK,
              indent: float = 0.0, line_h: float | None = None, gap: float = 1.0) -> None:
        pdf = self.pdf
        self._font(size, bold, color)
        pdf.set_x(pdf.l_margin + indent)
        pdf.multi_cell(pdf.epw - indent, line_h or size * 0.53, self.t(text), align="L",
                       new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if gap:
            pdf.ln(gap)

    def _note(self, text: str) -> None:
        self._para(text, size=9.5, color=INK2, gap=1.5)

    def _ensure(self, height: float) -> None:
        if self.pdf.will_page_break(height):
            self.pdf.add_page()

    def _heading(self, text: str, *, keep: float = 48.0) -> None:
        pdf = self.pdf
        self._ensure(keep)
        if pdf.get_y() > pdf.t_margin + 1:
            pdf.ln(3)
        pdf.start_section(text)
        self._font(15, True)
        pdf.cell(0, 8, self.t(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1)

    def _table(self, headers: Sequence[str], rows: Sequence[Sequence[Any]], widths: Sequence[float],
               aligns: Sequence[str], *, size: float = 9, empty: str = "None in this period.",
               width: float | None = None) -> None:
        pdf = self.pdf
        if not rows:
            self._note(empty)
            return
        shown = list(rows[:_MAX_TABLE_ROWS])
        head = [self.t(h) for h in headers]
        body = [[self.t("–" if v is None or v == "" else v) for v in r] for r in shown]
        total = min(width or pdf.epw, pdf.epw)
        col_widths = self._fit_widths(head, body, widths, total, size)
        self._font(size)
        pdf.set_fill_color(0)   # fpdf2 tables inherit a non-default fill colour as every cell's background
        pdf.set_draw_color(*AXIS)
        pdf.set_line_width(0.2)
        with pdf.table(
            col_widths=tuple(col_widths),
            text_align=tuple(aligns),
            width=total,
            align="LEFT",
            line_height=size * 0.5,
            padding=(1.0, _CELL_PAD),
            borders_layout="HORIZONTAL_LINES",
            headings_style=FontFace(emphasis="BOLD", color=INK, fill_color=TILE),
        ) as table:
            row = table.row()
            for h in head:
                row.cell(h)
            for r in body:
                row = table.row()
                for value in r:
                    row.cell(value)
        pdf.ln(2)
        if len(rows) > len(shown):
            self._note(f"{len(rows) - len(shown)} more rows are not shown.")

    def _fit_widths(self, head: Sequence[str], body: Sequence[Sequence[str]], weights: Sequence[float],
                    total: float, size: float) -> list[float]:
        """Column widths (mm) summing to ``total``: never narrower than the longest word of the heading or
        of a cell (capped), so words do not break mid-word; spare width follows ``weights``."""
        pdf = self.pdf
        pad = 2 * _CELL_PAD + 0.8
        mins = []
        for j, h in enumerate(head):
            self._font(size, True)
            need = max((pdf.get_string_width(w) for w in h.split()), default=0.0)
            self._font(size)
            for r in body:
                if j < len(r):
                    need = max(need, max((pdf.get_string_width(w) for w in r[j].split()), default=0.0))
            mins.append(min(need, _MAX_WORD_MM) + pad)
        spare = total - sum(mins)
        if spare <= 0:
            return [m * total / sum(mins) for m in mins]
        wsum = sum(weights) or 1.0
        return [m + spare * w / wsum for m, w in zip(mins, weights)]

    def _local(self, dt: datetime) -> datetime:
        return self.data.local(dt)

    # ------------------------------------------------------------------ sections
    def _title_block(self) -> None:
        pdf, d = self.pdf, self.data
        start, end = self._local(d.period_start), self._local(d.period_end)
        gen = self._local(d.generated_at)
        self._font(22, True)
        pdf.cell(0, 11, self.t("TactiDose report"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self._para(f"{d.patient.display_name} · Patient ID {d.patient.user_id}", size=14, bold=True, gap=1.5)
        self._para(f"Period: {fmt_date(start)}, {fmt_time(start)} – {fmt_date(end)}, {fmt_time(end)} "
                   f"({d.timezone}) · last {_days(d.days)}", gap=0.5)
        by = d.creator
        who = f" by {by.display_name} ({by.role})" if by is not None else ""
        self._para(f"Generated: {fmt_date(gen)}, {fmt_time(gen)}{who}", gap=0.5)
        dev = d.device
        if dev is not None:
            minutes = dev.manual_cooldown_minutes
            cooldown = (f"{minutes} minute{'' if minutes == 1 else 's'}" if minutes else "off")
            self._para(f"Device: {dev.name} ({dev.device_id}) · Cooldown after any drop: {cooldown} · "
                       f"Automatic scheduled drops: {'on' if dev.auto_drop_enabled else 'off'}",
                       size=10, color=INK2, gap=0.5)
        else:
            self._para("Device: none linked to this patient.", size=10, color=INK2, gap=0.5)
        pdf.ln(2)
        pdf.set_draw_color(*AXIS)
        pdf.set_line_width(0.3)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(3)

    def _summary(self) -> None:
        s = self.stats
        doses, drops = s["doses"], s["drops"]
        self._heading("Summary", keep=75)
        decided = doses["dispensed"] + doses["missed"]
        adherence_caption = (f"{doses['dispensed']} of {decided} scheduled doses dropped" if decided
                             else "No scheduled doses decided yet")
        open_doses = doses["pending"] + doses["hardware_errors"]
        missed_caption = "Not dropped within their window"
        if open_doses:
            missed_caption += f" · {open_doses} still open"
        refused = drops["refused_by_reason"]
        refused_caption = " · ".join(f"{reason_label(r)} {n}" for r, n in list(refused.items())[:2]) or "None"
        problems = drops["failed"] + drops["uncertain"]
        problem_caption = f"{drops['failed']} failed · {drops['uncertain']} uncertain"
        if drops["needs_review"]:
            problem_caption += f" · {drops['needs_review']} to review"
        tiles = [
            ("Adherence", fmt_pct(doses["adherence_rate"]), adherence_caption),
            ("On time", str(doses["on_time"]),
             f"Within {s.get('on_time_minutes', 15)} min of schedule · {doses['late']} late"),
            ("Missed doses", str(doses["missed"]), missed_caption),
            ("Drops on request", str(drops["on_request_drops"]),
             (f"{drops['manual_drops']} app · {drops['agent_drops']} assistant · "
              f"{drops['button_drops']} device button")),
            ("Refused requests", str(drops["refused_requests"]), refused_caption),
            ("Drop problems", str(problems), problem_caption),
        ]
        pdf = self.pdf
        gap = 4.0
        w = (pdf.epw - 2 * gap) / 3
        h = 30.0
        y = pdf.get_y()
        for i, (label, value, caption) in enumerate(tiles):
            col, row = i % 3, i // 3
            self._tile(pdf.l_margin + col * (w + gap), y + row * (h + gap), w, h, label, value, caption)
        pdf.set_xy(pdf.l_margin, y + 2 * h + gap + 3)

    def _tile(self, x: float, y: float, w: float, h: float, label: str, value: str, caption: str) -> None:
        pdf = self.pdf
        pdf.set_fill_color(*TILE)
        pdf.rect(x, y, w, h, style="F", round_corners=True, corner_radius=1.5)
        pdf.set_xy(x + 4, y + 3)
        self._font(10, True, INK2)
        pdf.cell(w - 8, 5, self.t(label))
        pdf.set_xy(x + 4, y + 8.5)
        self._font(22, True)
        pdf.cell(w - 8, 10, self.t(value))
        self._font(9, False, INK2)
        lines = pdf.multi_cell(w - 8, 4.2, self.t(caption), align="L", dry_run=True, output="LINES")
        if len(lines) > 2:
            lines = [lines[0], lines[1].rstrip() + "…"]
        for j, line in enumerate(lines):
            pdf.set_xy(x + 4, y + 20 + j * 4.2)
            pdf.cell(w - 8, 4.2, line)

    def _adherence(self) -> None:
        rows = self.stats["per_day"]
        self._heading("Adherence by day", keep=85)
        self._note("Share of each day's scheduled doses that dropped: dropped ÷ (dropped + missed). "
                   "A short grey dash means no scheduled dose was decided that day. "
                   "Exact numbers are in the table below the chart.")
        self._chart(rows)
        table_rows = []
        for r in rows:
            day = datetime.fromisoformat(r["date"])
            table_rows.append([
                fmt_day(day), r["scheduled"], r["dispensed"], r["on_time"], r["late"], r["missed"],
                r["pending"] or "", fmt_pct(r["adherence_rate"]), r["on_request_drops"], r["refused"],
            ])
        self._table(
            ["Day", "Scheduled", "Dropped", "On time", "Late", "Missed", "Still open", "Adherence",
             "On request", "Refused"],
            table_rows, (3, 1, 1, 1, 1, 1, 1, 1, 1, 1),
            ("LEFT",) + ("RIGHT",) * 9,
        )

    def _chart(self, rows: Sequence[dict[str, Any]]) -> None:
        pdf = self.pdf
        n = len(rows)
        axis_w, plot_h, top_pad, band = 12.0, 42.0, 6.0, 9.0
        self._ensure(top_pad + plot_h + band + 4)
        plot_x = pdf.l_margin + axis_w
        plot_w = pdf.epw - axis_w
        y_top = pdf.get_y() + top_pad
        base = y_top + plot_h
        pdf.set_line_width(0.2)
        pdf.set_draw_color(*GRID)
        for pct in (25, 50, 75, 100):
            y = base - plot_h * pct / 100
            pdf.line(plot_x, y, plot_x + plot_w, y)
        self._font(8, False, INK2)
        for pct in (0, 25, 50, 75, 100):
            y = base - plot_h * pct / 100
            pdf.set_xy(pdf.l_margin, y - 1.6)
            pdf.cell(axis_w - 2, 3.2, f"{pct}%", align="R")
        if n:
            slot = plot_w / n
            bar_w = min(slot * 0.6, 6.35)            # 24 px cap
            every = max(1, math.ceil(n / 12))
            labelled = _bars_to_label(rows)
            for i, r in enumerate(rows):
                cx = plot_x + slot * (i + 0.5)
                rate = r["adherence_rate"]
                if rate is not None and rate > 0:
                    h = plot_h * min(rate, 1.0)
                    pdf.set_fill_color(*BAR)
                    radius = max(0.0, min(1.0, bar_w / 2, h))
                    pdf.rect(cx - bar_w / 2, base - h, bar_w, h, style="F",
                             round_corners=("TOP_LEFT", "TOP_RIGHT") if radius > 0 else False,
                             corner_radius=radius)
                elif rate is None:
                    pdf.set_draw_color(*MUTED)
                    pdf.set_line_width(0.4)
                    half = max(bar_w / 3, 0.4)
                    pdf.line(cx - half, base - 1.2, cx + half, base - 1.2)
                if i in labelled and rate is not None:
                    self._font(8, True)
                    text = fmt_pct(rate)
                    tw = pdf.get_string_width(text) + 1
                    pdf.set_xy(cx - tw / 2, base - plot_h * min(rate, 1.0) - 4.4)
                    pdf.cell(tw, 3.6, text, align="C")
                if (n - 1 - i) % every == 0:
                    self._font(7.5, False, INK2)
                    day = datetime.fromisoformat(r["date"])
                    text = f"{r['weekday']} {day.day}"
                    lw = slot * every
                    pdf.set_xy(cx - lw / 2, base + 1.5)
                    pdf.cell(lw, 3.6, text, align="C")
        pdf.set_draw_color(*AXIS)
        pdf.set_line_width(0.3)
        pdf.line(plot_x, base, plot_x + plot_w, base)
        pdf.set_xy(pdf.l_margin, base + band)
        self._font(11)

    def _medications(self) -> None:
        self._heading("Medications")
        rows = []
        for m in self.stats["per_medication"]:
            name = m["name"] + (f" ({m['strength']})" if m.get("strength") else "")
            if not m.get("active", True):
                name += " — archived"
            dropped = f"{m['dispensed']}" + (f" ({m['late']} late)" if m["late"] else "")
            rows.append([
                name,
                ", ".join(str(c) for c in m["containers"]) or "–",
                "; ".join(m["schedule"]) or "No schedule",
                m["scheduled"], dropped, m["missed"], fmt_pct(m["adherence_rate"]),
                m["on_request_drops"], m["pill_count"], _supply_text(m["days_of_supply"]),
            ])
        self._table(
            ["Medication", "Container", "Schedule", "Scheduled", "Dropped", "Missed", "Adherence",
             "On request", "Pills left", "Days of supply"],
            rows, (30, 2, 14, 2, 4, 2, 2, 2, 2, 2),
            ("LEFT", "CENTER", "LEFT") + ("RIGHT",) * 7, empty="No medications on record.",
        )

    def _issues(self) -> None:
        self._heading("Missed, failed and uncertain")
        issues = self.stats.get("issues", [])
        total = self.stats.get("issues_total", len(issues))
        rows = []
        for it in issues:
            at = self._local(datetime.fromisoformat(it["at"]))
            kind = it["kind"]
            if kind == "MISSED":
                what, detail = "Missed dose", "Not dropped within the dose window"
                if it.get("reason"):
                    detail += f" (last device result: {it['reason']})"
            elif kind == "FAILED":
                what = "Drop failed"
                detail = f"Nothing dropped: {reason_label(it.get('reason'))}"
            else:
                what = "Drop uncertain"
                detail = ("Device could not confirm the drop — needs review by doctor or family"
                          if it.get("needs_review") else "Reviewed" + (f": {it['review_note']}"
                                                                       if it.get("review_note") else ""))
            med = it.get("medication_name") or "–"
            if it.get("container_number"):
                med += f" (container {it['container_number']})"
            rows.append([fmt_datetime(at), what, med, source_label(it.get("source")), detail])
        self._table(["When", "What", "Medication", "Requested by", "Detail"], rows,
                    (6, 3, 8, 3, 14), ("LEFT",) * 5, empty="No missed doses and no failed or uncertain drops.")
        if total > len(issues):
            self._note(f"Showing the latest {len(issues)} of {total} entries.")

    def _refused(self) -> None:
        self._heading("Refused requests")
        drops = self.stats["drops"]
        refused = [d for d in self.data.drops if d.status == "DENIED" and d.source != "schedule"]
        skipped = [d for d in self.data.drops if d.status == "DENIED" and d.source == "schedule"]
        if not refused:
            self._note("No drop request was refused in this period.")
        else:
            self._note("A safety rule turned these requests down, so nothing was dropped.")
            reason_rows = [[reason_label(r), n] for r, n in drops["refused_by_reason"].items()]
            if reason_rows:
                self._table(["Reason", "Requests"], reason_rows, (4, 1), ("LEFT", "RIGHT"), width=110)
            recent = refused[-30:]
            rows = []
            for d in recent:
                med = d.medication_name or "–"
                if d.container_number:
                    med += f" (container {d.container_number})"
                rows.append([fmt_datetime(self._local(d.requested_at)), source_label(d.source), med,
                             reason_label(d.reason)])
            self._table(["When", "Via", "Medication", "Reason"], rows, (5, 3, 8, 9), ("LEFT",) * 4)
            if len(refused) > len(recent):
                self._note(f"Showing the latest {len(recent)} of {len(refused)} refused requests.")
        if skipped:
            by_reason: dict[str, int] = {}
            for d in skipped:
                by_reason[reason_label(d.reason)] = by_reason.get(reason_label(d.reason), 0) + 1
            parts = ", ".join(f"{k}: {v}" for k, v in sorted(by_reason.items(), key=lambda kv: -kv[1]))
            self._note(f"Automatic scheduled drops skipped by the rules: {len(skipped)} ({parts}).")

    def _inventory(self) -> None:
        self._heading("Inventory now")
        rows = []
        for c in self.stats["inventory"]:
            name = c["medication_name"] or "No medication"
            if c.get("strength"):
                name += f" ({c['strength']})"
            if c["medication_id"] is None:
                status = "Not in use"
            elif c["empty"]:
                status = "Empty"
            elif c["low_stock"]:
                status = "Low stock"
            else:
                status = "OK"
            if not c.get("active", True):
                status += " (container disabled)"
            per_day = c["doses_per_day"]
            rows.append([c["container_number"], name, c["pill_count"], c["capacity"], c["low_stock_threshold"],
                         status, _per_day_text(per_day) if c["medication_id"] is not None else "–",
                         _supply_text(c["days_of_supply"])])
        self._table(["Container", "Medication", "Pills left", "Capacity", "Low-stock alert at", "Status",
                     "Doses per day", "Days of supply"],
                    rows, (1, 12, 1, 1, 1, 2, 1, 1), ("CENTER", "LEFT") + ("RIGHT",) * 3 + ("LEFT",)
                    + ("RIGHT",) * 2, empty="No containers on record.")
        self._note("Days of supply = pills left ÷ scheduled doses per day; it does not include extra "
                   "drops on request.")

    def _narrative(self) -> None:
        self._heading("Conversation summary")
        n = self.narrative
        if n.source == "gemini":
            self._note(f"Written by Gemini ({n.model or 'AI'}) from the conversation log. It quotes the "
                       "patient and does not diagnose or advise; check it against the excerpts below.")
        else:
            self._note("Automatic summary from the dispenser records and the conversation log (no AI).")
        for raw in (n.text or "").split("\n"):
            line = raw.rstrip()
            if not line.strip():
                self.pdf.ln(1.5)
                continue
            if line.startswith("  - "):
                self._para("• " + line[4:], size=10.5, indent=9, gap=0.4)
            elif line.startswith("- "):
                self._para("• " + line[2:], size=11, indent=3, gap=0.6)
            else:
                self._para(line, size=11, gap=0.6)

    def _excerpts(self) -> None:
        self._heading("Conversation excerpts")
        if not self.excerpts:
            self._note("No conversations with the assistant in this period.")
            return
        self._note(f"Selected messages between the patient and the assistant, oldest first; possible "
                   f"symptoms, concerns and pill requests are included first. Times are {self.data.timezone}.")
        pdf = self.pdf
        started_at = {c.conversation_id: c.started_at for c in self.data.conversations}
        current: int | None = None
        for ex in self.excerpts:
            if ex.conversation_id != current:
                current = ex.conversation_id
                self._ensure(22)
                pdf.ln(1)
                started = started_at.get(ex.conversation_id, ex.at)
                self._para(f"Conversation started {fmt_datetime(self._local(started))}", size=9.5, bold=True,
                           color=INK2, gap=0.3)
            speaker = {"patient": "Patient", "assistant": "Assistant", "dispenser": "Dispenser"}.get(
                ex.speaker, ex.speaker.title())
            if ex.speaker == "patient" and ex.input_mode == "voice":
                speaker += " (voice)"
            self._ensure(14)
            self._para(f"{fmt_datetime(self._local(ex.at))} — {speaker}", size=9.5, bold=True, color=INK2,
                       indent=3, gap=0.2)
            self._para(ex.text or "(empty message)", size=10.5, bold=ex.speaker == "patient", indent=9, gap=1.2)

    def _about(self) -> None:
        self._heading("About this report", keep=60)
        minutes = self.stats.get("on_time_minutes", 15)
        for text in (
            (f"On time: dropped no later than {minutes} minutes after the scheduled time (an early drop "
             "within the dose window also counts)."),
            ("Adherence: scheduled doses dropped ÷ (dropped + missed). Doses still open and doses skipped "
             "by doctor or family are not counted."),
            ("Drops on request: pills dropped because the patient asked (app button, assistant or device "
             "button). Such a drop can also satisfy a scheduled dose, which is then not dropped again."),
            ("Refused requests: a safety rule (cooldown, empty container, dose already dropped, device "
             "unavailable, pending review) turned the request down; nothing was dropped."),
            ("Uncertain: the device could not confirm whether a pill dropped. It counts as a drop for the "
             "cooldown and must be reviewed by doctor or family."),
        ):
            self._para("• " + text, size=10, indent=3, gap=0.6)
        if self.stats.get("truncated"):
            self._para("• Very long period: only the newest records of "
                       f"{', '.join(self.stats['truncated'])} are included.", size=10, indent=3, gap=0.6)
        self.pdf.ln(2)
        self._para(DISCLAIMER + " It must not be used to make treatment decisions.", size=10, bold=True)


# --------------------------------------------------------------------------- helpers


def _days(days: int) -> str:
    return f"{days} day" if days == 1 else f"{days} days"


def _fit_text(pdf: FPDF, text: str, width: float) -> str:
    """``text`` shortened with an ellipsis so it fits ``width`` in the current font."""
    if pdf.get_string_width(text) <= width:
        return text
    lo, hi = 0, len(text)
    while lo < hi:                      # longest prefix that fits together with the ellipsis
        mid = (lo + hi + 1) // 2
        if pdf.get_string_width(text[:mid].rstrip() + "…") <= width:
            lo = mid
        else:
            hi = mid - 1
    return text[:lo].rstrip() + "…"


def _supply_text(value: float | None) -> str:
    if value is None:
        return "–"
    if value >= 100:
        return f"{value:.0f}"
    return f"{value:.1f}".rstrip("0").rstrip(".") if value % 1 else f"{value:.0f}"


def _per_day_text(value: float) -> str:
    if not value:
        return "0"
    return f"{value:.2f}".rstrip("0").rstrip(".")


def _bars_to_label(rows: Sequence[dict[str, Any]]) -> set[int]:
    """Direct labels only where they matter: the latest day with data and the days below 100%
    (or just the lowest one when there are many)."""
    idx = [i for i, r in enumerate(rows) if r["adherence_rate"] is not None]
    if not idx:
        return set()
    chosen = {idx[-1]}
    below = [i for i in idx if rows[i]["adherence_rate"] < 1]
    if len(below) <= 6:
        chosen.update(below)
    else:
        chosen.add(min(below, key=lambda i: (rows[i]["adherence_rate"], i)))
    return chosen
